### PR TITLE
Make create account responsive #645

### LINKED ISSUE #645: Make the create account page responsive
**Describe the bug**

The create account page is not responsive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `localhost:3000/sign-up`
2. See error

**Expected behaviour**

Everything should be centred in the middle of the page, even for mobile devices. 

**Screenshots**

At 2560x1440p:
image

**Additional context**

Branch from `0.2.0` and create a pull request to go back into it.

See #627. The width of the text fields should be the same and the logo should be the same size.

### PR DESCRIPTION
**Pull request by ofvoler**
## Summary of change

Centered all content on the create account page both vertically and horizontally - should look almost identical to the login page. Content is also responsive to all screen sizes.

I also centered the 'incorrect email/password' error message on the login page, per request.

## Additional context

desktop
half desktop
narrow
mobile

## Related issue

Closes #645 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this! Could you also please centre the password strength status text?

**Comment by ofvoler** [comment]
Sure!

**Comment by ofvoler** [comment]
Okay, that should do it. Let me know if there's anything else I should add.

password strength text

**Review by knjk04 — APPROVED** [review]
This is excellent! Thanks a lot!

**Pull request merged**
