### PR TITLE
Make login page responsive #599

### LINKED ISSUE #599: Make the login page responsive
**Describe the bug**

The logo does not appear where want it to at different screen resolutions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `localhost:3000`
2. See error

**Expected behaviour**

**Screenshots**

Fine at 2560x1440. This is what we want it to look at different resolutions:
image

1920x1080. The logo is slightly too far to the right and too close to the 'username' field
image

Too far to the right and overlaps with the username text field 
image

**Additional context**

Branch: `0.2.0`

### PR DESCRIPTION
**Pull request by ofvoler**
## Summary of change

Make the login content centered and responsive.

## Additional context

desktop
tablet
mobile

## Related issue

Closes #599 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this!

image

It might be quite hard to tell from the picture above, but the logo looks a bit blurry at 2560x1440. 

image

Also, while typing into the password field fills most of the width, it doesn't for the username field.

Would it be possible to fix the above two points?

**Comment by ofvoler** [comment]
Yes, definitely! I have no clue why the username field is like that, since I'm using the same CSS for both of them, but I'll try to figure that out.

**Comment by ofvoler** [comment]
I think all of those changes should be addressed with the four new commits! 

I'm not sure why there's a test failure, since the project builds fine for me. I was also able to successfully merge the feature branch into an updated 0.2.0 in my local repo, so it shouldn't be a merge issue or outdated code. Please let me know if there's something I can do to fix that!

**Comment by knjk04** [comment]
@ofvoler Thanks! I'll review this shortly

Don't worry about the test failures, they're not related to this issue (we don't have any tests on the frontend yet). I'll create separate issues to fix those.

**Review by knjk04 — APPROVED** [review]
Thanks a lot, this is great!

**Pull request merged**
