### PR TITLE
Change email address 280

### LINKED ISSUE #280: Change email address
**Is your feature request related to a problem? If so, please describe.**
A user cannot currently change the email address they signed up with.

**Describe the solution you'd like**
Create a new endpoint that allows us to change their email address. We should re-authenticate to handle the time of check to time of use issue (TOCTOU).

**Additional context**
Branch from `0.2.0`. When you're ready, create a pull request with `0.2.0` as the destination branch 

(Once #278 is implemented, we should also send a verification code to the new email address)

### PR DESCRIPTION
**Pull request by SeonghoLee4**
## Summary of change

Create change email address endpoint.
Add UserControllerTest.java

## Related issue

Closes #280 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by knjk04** [comment]
How are you getting on with this?

**Comment by knjk04** [comment]
Discussed offline

**Comment by knjk04** [comment]
@SeonghoLee4 Could you also resolve the merge conflicts?

**Comment by SeonghoLee4** [comment]
> @SeonghoLee4 Could you also resolve the merge conflicts?

Is the conflict about the build failure?

**Comment by knjk04** [comment]
@SeonghoLee4 The conflict is a merge conflict. This means that both you've modified parts of the code in your feature branch that have also been modified in `0.2.0` and Git doesn't know how to resolve the conflicts automatically. See this guide for more information: https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts

The build failure is to do with a different issue

**Comment by knjk04** [comment]
@SeonghoLee4 How are you getting on with this?

**Comment by knjk04** [comment]
Closing due to no response

**Pull request closed without merging**
