### PR TITLE
Adds instructions on how to run with Vaadin live reload

### LINKED ISSUE #407: Fix Vaadin live reload
image

Vaadin live reload does not currently work. This can make development a lot slower.

### PR DESCRIPTION
**Pull request by dmitraver**
## Summary of change

As discussed here https://teambookproject.slack.com/archives/C01AGDC5X1S/p1601991038033600, there is no way to make live reload work when the application is run as a JAR because vaadin doesn't support passing authentication details when using live reload feature. This change adds a note to the readme that shows how to run application locally with live reload feature enabled.

## Related issue

Closes #407 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by dmitraver** [comment]
hi @knjk04, is there anything else I need to add here?

**Comment by knjk04** [comment]
Hi @dmitraver,

I was just waiting for your reply on Slack. Also, I took a look today and encountered an error, so I'll look into this further later.


Thanks for creating this PR!

**Comment by dmitraver** [comment]
Haven't seen the message, didn't get notification for some reason. Replied there in thread.

**Review by knjk04 — APPROVED** [review]
Thanks for finding the solution to live reload! I also particularly liked the explanation for why someone may want to use Vaadin Live Reload. I've moved some things around but kept the crux of your work in.

**Pull request merged**
