### PR TITLE
Only call API if the password strength is 'very strong'

### LINKED ISSUE #613: Only call API if the password strength is 'very strong'
**Describe the solution you'd like**
We're using [zxcvbn](https://github.com/dropbox/zxcvbn) as our password strength estimator. We only want to call `sendRegisterRequest()` in `onCreateAccountClicked()` if the password strength is 'very strong'.

```ts
  onCreateAccountClicked() {
    // ...

    if (!this.state.areCredentialsInvalid) {
      this.sendRegisterRequest()
    }
  }
```

**Additional context**
`0.2.0 branch`

### PR DESCRIPTION
**Pull request by osopromadze**
## Summary of change

Added password strength check before calling API.

## Related issue

Closes #613 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by osopromadze** [comment]
@knjk04 fixed to call API if password strength equal 4 (very strong), but at this moment it does not say to user what is happening and why registration stopped. Maybe would be good if we add some message in case of weak password, for example something like this:
image

**Comment by osopromadze** [comment]
This branch is created on top of 0.2.0, and there were failing tests in the backend, which are fixed in #620.

**Comment by knjk04** [comment]
> Maybe would be good if we add some message in case of a weak password, for example, something like this:

I definitely agree! 

Thanks for working on this (and for fixing the failing tests)! I'll review this shortly

**Review by knjk04 — CHANGES_REQUESTED** [review]
Thanks for working on this!

Could you please replace the hard-coded `4` with a constant called `VERY_STRONG`?

**Comment by osopromadze** [comment]
> Thanks for working on this!
> 
> Could you please replace the hard-coded `4` with a constant called `VERY_STRONG`?

OK @knjk04, no problem. Is there some file with application-wide constants? or we do it locally in the component.

**Comment by osopromadze** [comment]
@knjk04 done. Created enum with values of password strength in the Register component.

**Review by osopromadze — COMMENTED** [review]
@knjk04 done. Created enum with values of password strength in the Register component.

**Review by knjk04 — APPROVED** [review]
Thanks!

**Comment by knjk04** [comment]
Small tip for the future: it may be easier to not use quotation marks and apostrophes as you and the reviewer won't have to escape it or surround with a different type

**Pull request merged**
