### PR TITLE
move CustomShelfUtils methods to CustomShelfService

### LINKED ISSUE #434: Refactor CustomShelfUtils to have static methods
Currently, `CustomShelfUtils` is a utility class that needs to be instantiated. Refactor this so that it cannot be instantiated and its methods are all static

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### PR DESCRIPTION
**Pull request by tw-ayush**
Make `CustomShelfUtils` class methods static. Also added a custom class for dependency injection in any static class.

## Relevant issue

Closes #434

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x]  Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).

  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
@tw-ayush Thanks for creating this PR. We'll review this shortly

**Comment by knjk04** [comment]
Apologies for the delay in reviewing this. There's a backlog of work right now. We are looking into this and we'll get back to you soon

**Review by knjk04 — CHANGES_REQUESTED** [review]
@tw-ayush Thanks a lot for working on this, and once again, I'm very sorry it's taken so long for us to get back to you.

I've thought about this a lot and I'm thinking that perhaps we shouldn't autowire the static class. Instead, what about moving the `CustomShelfUtils` methods to `CustomShelfService`?

**Comment by tw-ayush** [comment]
what we can do is keep the data members in static class only and move the call to methods to operate on those in service class (which is not static).

eg : 
` public static List<@NotNull String> getCustomShelfNames() {` 
remains in CustomShelfUtils.java but this is can be called from service class.

**Comment by knjk04** [comment]
@tw-ayush We could do that, but I'm not so keen on the workaround to autowiring the static class. I think in this case it's better to move it to the service class.

**Comment by tw-ayush** [comment]
> @tw-ayush We could do that, but I'm not so keen on the workaround to autowiring the static class. I think in this case it's better to move it to the service class. Instead of creating a wrapper, the util methods should probably belong in the service class, anyway

then shall we delete this static/util class all together?

**Review by knjk04 — APPROVED** [review]
Thanks for working this & sorry, once again, for the long delay in reviewing this!

**Pull request merged**
