### PR TITLE
Search books api 772

### LINKED ISSUE #772: Connect frontend to Books API (GraphQL)
**Describe the solution you'd like**

image

Design a new search page that looks like the above image. We need 'Search' in the navigation bar with the material icon. The search page should be responsive.

After a user has typed in a query and presses enter, call [findByTitle](https://github.com/Project-Books/books-api/blob/main/src/main/java/com/karankumar/booksapi/datafetchers/BookDataFetcher.java#L56), passing in the search query (we'll assume it's a title for now and then build upon this later). For now, we can console.log the response until we have finished our mockup designs for this page.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

### PR DESCRIPTION
**Pull request by RivaD2**
## Connect Frontend to BooksAPI

**App.tsx**
- Adds `<Search />` to Router
- Uses `<ApolloProvider />` wrapper which wraps all other routes
- imports `{ apolloClient }` from `HttpClient.ts`

**HttpClient.ts**
- Set instance of `HttpClient()` to `httpClientInstance` variable and updated default export 
- Creates instance of Apollo Client specifying uri (`'http://localhost:8082/graphql'`) and cache properties and adds headers from `httpClientInstance`.

**package.json**
- Install for `@apollo/client` and imports associated with it (ApolloClient, InMemoryCache, ApolloProvider)

**Nav.tsx**
- Adds in additional `<NavItem />`  (we could think later about mapping over 1 NavItem for this as well :) )
- Added in material search icon and added style to display them side by side

**Search.tsx**

- Functional component with state for:
  - searchTerm
  - searchQuery
- Initializes state variable for `searchTerm` as string 
- Initializes state variable for `searchQuery` as string
- Creates method `searchBooks()` that handles default behavior of form and sets the search query to be the value of the search input
- Creates method `handleChange` for handling change event for the search input
- Takes in the `SearchResults` component and passes props of `query` to it

**SearchResults.tsx**

- Defines `ISearchResultProps` for `query` which are of type string
- This component takes in the search query provided from `Search` because it has to make the query 
- Creates const variable `FIND_BY_TITLE` and initializes to new `gql` query of `findByTitle`
- Uses `useQuery()` hook inside `searchBooks` function passing in query of `FIND_BY_TITLE` and variables needed to execute query (see docs here for [useQuery] (https://www.apollographql.com/docs/react/api/react/hooks/#usequery) 
- The query is of course whatever the user has typed into the search input

**Search.css**

- Adds styles for Search input (responsive style additons)

**Routes.tsx**

- Adds  `/search` route

## Additional context

**Search in Nav**

Screen Shot 2021-10-06 at 8 47 11 AM

**Search**

Screen Shot 2021-10-06 at 8 47 33 AM

**SearchResults console.logging `data` for now**
Screen Shot 2022-01-23 at 11 42 19 AM
Screen Shot 2022-01-23 at 12 05 01 PM

Success
## Related issue

Closes #772

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [ ] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@RivaD2 It looks like our linter is failing: https://github.com/Project-Books/book-project/runs/4914636403?check_suite_focus=true#step:4:9. Could you please look into this?

**Comment by RivaD2** [comment]
> [ ](/knjk04)
> ` [Remove package-lock](/Project-Books/book-project/pull/807/commits/c131372d56b2172671008cb9212ead9f4fbb5069)`

Hi there Karan.

I believe this is saying I need to install dependencies...
If I update my dependencies then it will generate a lock file and I will need to commit it. I see you removed a package.lock file on my branch on commit c131372. 

So is this failing because there is no package lock?If so, how do you want me to proceed regarding package.lock file?

**Comment by knjk04** [comment]
Hi @RivaD2, I ran `yarn install` in the frontend directory. This updated the yarn.lock file and it passes the linter now

**Review by knjk04 — APPROVED** [review]
Thanks a lot for your hard work on this!

**Comment by RivaD2** [comment]
> Thanks a lot for your hard work on this!

You are most welcome, I am happy to help! Thank you for all of your assistance :) 👍

**Pull request merged**
