### PR TITLE
Make view switcher sticky

### LINKED ISSUE #765: Make shelf/list view toggle 'sticky'
**Currently**

image

Currently, we display the toggle at the bottom of the page.

**Describe the solution you'd like**

See page 2 of our [mockups](https://www.figma.com/proto/MWYSlKNoyg3Ja3EAeectcQ/Book-Project-UI-Copy?node-id=1%3A2&scaling=min-zoom). The toggle is always present, even when you scroll up or down.

**Additional context**
- Be sure to read the contributing guidelines first!

### PR DESCRIPTION
**Pull request by arshxyz**
## Summary of change

Changed some CSS to make the shelf view toggle on `My Books` sticky. This is in line with the Figma mockups.

## Additional context

This is what it looks like now:
image

## Related issue

Closes #765 

## Pull request checklist

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this!

As it stands, you won't show up as a contributor. One possible reason for this is because your email address attached to your commits is/are not the same as those associated with your GitHub account. 

In line with the ['Ensure your email address on your commits are correct'](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#ensure-your-email-address-on-your-commits-are-correct) section our style guide, you'll need to fix this. Instructions on how to do so can be found [here](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#rewriting-pushed-commits-with-a-different-email-address)

For more information, see https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile

I'll mark this PR as a draft. Feel free to request a review when you have fixed this.

If you need a hand with this, let us know over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ).

**Comment by arshxyz** [comment]
@knjk04 Hey, I have fixed my local GitHub email. Let me know if there's still an issue.

**Comment by knjk04** [comment]
Looks good locally for me.

@RivaD2 Are you happy with the CSS changes?

**Review by knjk04 — APPROVED** [review]
Thanks for working on this! This looks great and as we hoped!

**Pull request merged**
