### PR TITLE
create statistics page

### LINKED ISSUE #813: Create statistics page
**Describe the solution you'd like**
image

Create a statistics page that looks like the above. For the image, you can use one of the existing images we're already using. This data should be hardcoded for now (we'll later fetch this from the backend).

You'll also need to add a new item to the navigation bar (you can ignore the fact that the navigation bar looks slightly different).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

### PR DESCRIPTION
**Pull request by Girish-Bharadwaj**
## Summary of change

Created statistics page

## Additional context

Screenshot for UI: https://drive.google.com/file/d/1wsXOloqfYEvGZzYCC53Rvpk5wOxClW8w/view

## Related issue

Closes #813 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
Hi @Girish-Bharadwaj, thanks for working on this! The linter is failing -- could you please look into this?

**Comment by Girish-Bharadwaj** [comment]
I will fix the issue and merge again

**Comment by knjk04** [comment]
Hi @Girish-Bharadwaj, how are you getting on with fixing the linter issue?

**Comment by Girish-Bharadwaj** [comment]
@knjk04 Fixed the issue

**Pull request closed without merging**
