### PR TITLE
Feature: testcontainer support for integration tests

### LINKED ISSUE #917: Use Testcontainers instead of h2 for integration tests
**Describe the solution you'd like**
Use Testcontainers instead of h2 for integration tests so that we are actually using a PostgreSQL database.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

### PR DESCRIPTION
**Pull request by anugrahsinghal**
## Summary of change

Adds Testcontainer support for integration tests

## Related issue

Closes #917 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@anugrahsinghal Thanks for working on this! It looks like the conflicts are related to indentation.

Could you please run the [google-java-format](https://github.com/google/google-java-format) plugin (available for IntelliJ, Eclipse, etc.) on the files you have modified?

**Comment by anugrahsinghal** [comment]
hey @knjk04, have taken care of the formatting.

**Comment by knjk04** [comment]
Hi @anugrahsinghal, thanks for fixing this & apologies for the delay. Something has come up at home, but I'll review this soon

**Comment by anugrahsinghal** [comment]
hey @knjk04, thanks for letting me know.
Hope all is well :)
The PR is going nowhere, take care :)

**Pull request closed without merging**
