### PR TITLE
Verify password strength 688

### LINKED ISSUE #688: Verify password strength
**Describe the solution you'd like**
Check that the password strength is very strong on the backend with zxcbn4j. If it isn't, we shouldn't save the user/update the user's password. We need to update our controller endpoints to notify the frontend why the operation was not successful.

**Additional context**
Branch from `0.2.0` and set it as the destination branch in your pull request.

### PR DESCRIPTION
**Pull request by BOYLOVEOI**
## Summary of change
To verify the user password's strength, in the UserService class, I have imported Zxcvbn and instantiated an object of class Strength from Zxcvbn to get a numerical value for the strength of the user's password; furthermore, I have created an additional if statement that states that if the user's score (retrieved from Strength.getScore) is less than or equal to 2 (scores ranging from "Poor" to "Fair" based on the Zxcvbn's scale) then a ConstraintViolationException is thrown (thus, only "Good" to "Very Strong" passwords are accepted).

## Related issue

Closes #688

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [ ] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [ ] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [ ] Ensure code changes pass all tests

- [ ] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [ ] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [ ] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [ ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by knjk04** [comment]
Hi Paul,

>  Branch from 0.2.0 and set it as the destination branch in your pull request.

Note that as specified above (taken from the issue description), we asked that you create your feature branch from `0.2.0` and set it as the destination branch in your pull request. We're no longer using Vaadin. 

I'll close this PR as it is not valid. Let us know if you need a hand with anything

**Comment by BOYLOVEOI** [comment]
Hello Karan,

Thank you for notifying me of the error. Could you explain what you meant by "we asked that you create your feature branch from 0.2.0 and set it as the destination branch in your pull request,"? I am sorry for the errors, as it is my first time trying Github, it's currently a learning process for me right now. But still, thank you for the help and guidance, and I hope that I am able to contribute to your awesome proejct!

Thank You.
Paul

**Comment by knjk04** [comment]
Hello Paul,

No need to apologise, I appreciate that be have been quite confusing if this is your first time. I'll step through things in some more detail.

`create your feature branch from 0.2.0`

On your [VerifyPasswordStrength-88 branch](https://github.com/BOYLOVEOI/book-project/tree/VerifyPasswordStrength-688), I can see Vaadin-related files (a full-stack framework that we were using before). This was for our 0.1.0 release. For our 0.2.0 release, we are recreating (and redesigning) our frontend in 0.2.0. The backend is also changing.

What you need to do:
1. Remove your existing feature branch locally (on your machine): `git branch -d VerifyPasswordStrength-88`
2. Remove the existing feature branch remotely (from your fork on GitHub): `git push origin --delete VerifyPasswordStrength-88`
3. Switch to the `0.2.0` branch: `git checkout 0.2.0`
4. Pull the latest changes from the remote (what's on GitHub) into your local 0.2.0 branch: `git pull origin 0.2.0`
5. Create your feature branch from 0.2.0: `git checkout -b VerifyPasswordStrength-88` (note that while `checkout` is used to switch the branches, the `-b` flag is a nice shorthand that tells Git to also create the branch -- so you're creating a branch and then switching to it)
6. Do your work. Make small, meaningful commits (see the contributing guidelines)
7. Once ready, create a pull request and set the destination branch of the pull request to 0.2.0. In other words, we want to merge the work you created in `VerifyPasswordStrength-88` into `0.2.0`.

> create a pull request and set the destination branch of the pull request to 0.2.0. In other words, we want to merge the work you created in `VerifyPasswordStrength-88` into `0.2.0`

image

The above image shows that in this pull request, you want to merge `VerifyPasswordStrength-88` (not correct).

image

In the image above, I'm setting the base branch, or destination branch, as `0.2.0`. The 'feature branch' is `auto-incrementing-id-637`. 

I hope this helps. If you need any further help, feel free to create a GitHub discussion or ask on the #book-project channel on our Slack workspace

**Comment by BOYLOVEOI** [comment]
Hello Karan,

Thank you for the guidance, and as the last days of my semester are coming up (this coming Monday), I will be a bit busy until then. However, once I am finished for this semester I would love to continue to work on this issue if that is okay with you! If you are in a time crunch (which I wholeheartedly understand) then I am completely fine if you were to assign this issue to another user. Once again, thank you for the guidance, and I look forward to continue working on the Book Project!

Thank You,
Paul

**Comment by knjk04** [comment]
Hello Paul,

That's completely fine. Thanks for the update!

**Pull request closed without merging**
