### PR TITLE
Password reset modal 677

### LINKED ISSUE #677: Create password reset confirmation modal
**Describe the solution you'd like**
image

Create the password reset confirmation modal as shown above. This modal should be responsive and use our existing modal component as a starting point. 

As with our other modal, this modal should show in the middle of the screen.

**Additional context**
First, a user should click on the 'Forgot password' link:
image

Then, the user should enter an email address and click on the 'Send me a password reset link' button:
image

Finally, the password reset modal should appear (later on, we'll only show this final modal if we get a successful response from the backend).

### PR DESCRIPTION
**Pull request by RivaD2**
## Created the PasswordResetModal. This modal is responsive and uses the existing modal component as a starting point.
As with the other modal (ForgotPasswordModal), this modal shows in the middle of the screen. It shares a stylesheet with ForgotPasswordModal.

**PasswordResetModal.tsx**
- imported in base Material-UI Modal and `IModal` props to` PasswordResetModal`
- Passed `open: boolean` and `onClose: () =>` to Modal 
- Changed `modal-desc` (modal description) to match design provided
- passed `onClose` prop to button so when `Done` is clicked, the new Modal closes
- imported in stylesheet from `forgotPasswordModal` as both share the same styles
  - I then changed all classNames to match `ForgotPasswordModal` so they could easily share the same styles/styles would be reusable

**Login.tsx**
- Imported in the `PasswordResetModal` and passed two props: 
  - `open: boolean` which uses state to show `PasswordResetModal`
  -  `onClose: () => void` prop which tells the modal to close by passing the method `onPasswordResetModalClose`
  - Added methods:
    - `onPasswordResetModalClose()`
    - `onPasswordResetClicked()` 
 
**ForgotPasswordModal.tsx**
- Email component was brought in as part of my last PR (when I was creating `ForgotPasswordModal` so everything was already hooked up in that area
- Passed `onClick` prop to send me a password reset link Button
  - When user clicks the button, the  `onPasswordResetClicked()` method from parent component, `Login.tsx` is called 
  - Changed all classNames to be generic as modals share the same styles, and edited classNames accordingly in CSS

## Additional context

https://user-images.githubusercontent.com/67027945/116008797-35884800-a5cb-11eb-9337-a70dd2f19e61.mov

## Related issue

Closes #677

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [] Ensure code changes pass all tests 

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by knjk04** [comment]
Great work, thanks a lot!

**Review by knjk04 — APPROVED** [review]

**Comment by RivaD2** [comment]
@knjk04 thank you :)

**Comment by knjk04** [comment]
@RivaD2 As your work has consistently been great and you've been contributing regularly, it would be great to you have in our frontend team! If you're interested, feel free to join our Slack workspace so we can discuss this further

**Comment by RivaD2** [comment]
@knjk04 Wow, thank you so much! I would love to join the frontend team as I really enjoy working on this project.
I will join the Slack workspace now. :)

**Pull request merged**
