### PR TITLE
refactor unit tests CalculateReadingGoalTest

### PR DESCRIPTION
**Pull request by mofiebiger**
## Summary of change

This PR refactors the test `CalculateReadingGoalTest()` for the method `testHowFarAheadOrBehindSchedule()`. This test now includes two _boundary cases_ and a single _normal case_. 

Here the two _boundary cases_ look at the first week of the year and the last week of the year. The _normal case_ tests week 26 (the week exactly in the middle of the year). This week is most similar to other weeks compared to the first and last weeks of the year. 

Each case accounts for readers being ahead of schedule, behind schedule, and right on time. 

## Related issue

Closes: https://github.com/Project-Books/book-project/issues/393

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this, @mofiebiger! I'll mark this as a draft. When you've completed the PR description and you're ready for a review, feel free to mark this as 'ready for review'

**Comment by knjk04** [comment]
@mofiebiger How are you getting on with this pull request? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by mofiebiger** [comment]
Hi @knjk04! Thanks for checking in! The PR is ready to go. I tried to contact you via slack, but this came up.. 

Screenshot 2020-10-11 at 13 11 55

**Comment by knjk04** [comment]
@mofiebiger Oops, it looked like the invite link expired. Anyway, thanks for the update! We'll review shortly

**Comment by knjk04** [comment]
In case you still wanted to join our Slack workspace, here's an invite link that should work: https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ

**Review by knjk04 — CHANGES_REQUESTED** [review]
Thanks for working on this! This works as intended.

I've kept your tests but moved them to inner classes to improve readability -- I hope you don't mind. I think it's nice to have nested classes for the lower bound tests, upper bound and normal case (there were too many assertions in one test before and I think it's better from a single responsibility perspective to split it into smaller methods). Inside each one, it would be good to ensure the 3 sub-cases (behind, on and ahead of schedule) still work as intended. I've done some of this, but I've left the rest for you. The tests that I didn't move are because they don't fall into each sub-category (e.g. the last assertion in `showCorrectValueForUpperBound()` is not an on schedule test).

Also, I know this wasn't the issue description, but could you also add some tests for edge cases? Sorry for increasing the scope of the issue, it only just occurred to me.

Hopefully, this makes sense. If you have any suggestions for further improvements (e.g. if you're not so keen on this new style), feel free to let us know.

**Review by knjk04 — APPROVED** [review]
Thanks a lot for this! Great job!

**Pull request merged**
