### PR TITLE
Implementation of Refresh Token

### LINKED ISSUE #838: Add refresh tokens
**Is your feature request related to a problem? If so, please describe.**
This would enable the frontend to still know the user is authorised even after the page was refreshed.

**Describe the solution you'd like**

Provide a refresh token on login (we're already passing a JWT token, so we want to continue sending the JWT token in addition to the refresh token).

We need to read the httpCookie and check if it is a valid token. If so, we need to return a new JWT token and a new refresh token to the client. The new refresh cookie should be set via the Set-cookie header.

See [here](https://github.com/Project-Books/book-project/issues/722#issuecomment-867142758) for more information.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

### PR DESCRIPTION
**Pull request by varadeth**
## Summary of change

1. Handling of Unauthenticated if token expired
2. Send Refres…hToken via HttpOnly Cookie when logged in
3. Add Post API to verify refreshToken and if valid, send jwt token for login

## Related issue

Closes #838 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@varadeth Sorry, I haven't had a chance to look at this yet. I'll take a look at some point next week

**Comment by varadeth** [comment]
> @varadeth Sorry, I haven't had a chance to look at this yet. I'll take a look at some point next week

Sure. No issues

**Comment by knjk04** [comment]
@varadeth Sorry, I haven't forgotten about this, but I'll need a bit more time to review this

**Comment by knjk04** [comment]
@varadeth Once again, I'm very sorry. Something personal has come up, but I haven't forgotten about this!

**Comment by knjk04** [comment]
Sorry, still plan to look into this soon!

**Review by knjk04 — APPROVED** [review]
So sorry for the delay, but thanks a lot for this!

**Pull request merged**
