### PR TITLE
made grid dynamically resize as new rows are added

### LINKED ISSUE #301: Make BookGrid fill the entire page
**BookGrid is not utilizing the page height**

When a shelf contains more than 9 books, the book grid shows them in a list with a scroll bar although there is enough space on the page left to show them without the need for scrolling.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add multiple books to a shelf so that it contains at least 10
2. Select the shelf you added the books to in the "choose shelf" combobox
3. See error

**Expected behaviour**

The grid should make use of the whole height of the page instead of displaying a scroll bar. 

**Screenshots**
Much space left below the grid:
image

### PR DESCRIPTION
**Pull request by killerkc12**
## Summary of change

Make the grid dynamically expand as new books are added

## Additional context

image

## Related issue

Closes #301 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by killerkc12** [comment]
I'm happy to some contribute.

**Comment by knjk04** [comment]
@killerkc12 Thanks for creating a new PR for this issue. 

I noticed that you haven't completed the pull request description. I'll mark this as a draft for the time being

**Comment by knjk04** [comment]
I noticed that you marked this as 'ready for review' without completing the PR description. As this is a simple change, I've done this for you on your behalf. Please note for the future, however, that you are expected to complete this

**Review by knjk04 — APPROVED** [review]
Thanks for working on this, Kiran! Implementation-wise, this is great!

**Pull request merged**
