### PR TITLE
create export user's book data service

### PR DESCRIPTION
**Pull request by olusolaa**
A new pull request was #755 created, when I pushed my recent commit. I guess this happened because I change the name of the branch.

### CODE REVIEW

**Comment by knjk04** [comment]
@olusolaa How are you getting on with this?

**Comment by olusolaa** [comment]
> @olusolaa How are you getting on with this?

My bad, I will get back to you soon, I've been so busy lately.

**Comment by olusolaa** [comment]
Working on this right now will get back in a moment.

**Review by knjk04 — CHANGES_REQUESTED** [review]
@olusolaa Thanks for working on this! I've made some small adjustments, such as changes to the mapping names.

I'm getting a lazy initialization exception when I run this through Postman. Here's the stack trace: https://gist.github.com/knjk04/a5f214761ea07c1408eb97dc6226a0a4. Could you please take a look into this?

**Comment by knjk04** [comment]
Closing this PR so that you can raise a new one with a different branch name, but see the comment above. Aside from the exception, it looks good so far

**Pull request closed without merging**
