### PR TITLE
Refactor dark mode 723

### PR DESCRIPTION
**Pull request by ghost**
## Summary of change

Refactored dark mode to only apply to the nav section when toggled
- Text is visible on white background
- Input is visible on white background
- Font color changed to white for black nav bar  

## Additional context

Screen Shot 2021-10-30 at 10 04 16 PM
Screen Shot 2021-10-30 at 10 04 53 PM

## Related issue

#723

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@grace-ko Thanks for working on this!

image

I noticed that the commits aren't linked to your GitHub profile. Could you please fix this (see https://project-books.github.io/docs/development/contributing/#ensure-your-email-address-on-your-commits-are-correct)?

**Comment by grace-ko** [comment]
Please let me know if it's not fixed, thank you!

**Comment by knjk04** [comment]
image

@grace-ko It's still not showing up. We have a guide on how to fix this that may help: https://project-books.github.io/docs/development/how-to/rewrite-pushed-commits/

**Comment by grace-ko** [comment]
@knjk04 I think it's fixed now!

**Comment by knjk04** [comment]
@grace-ko Thanks for fixing that! 

This is what it looks like for me:

image

Do you know why this might be happening?

**Comment by grace-ko** [comment]
hmm looks ok on my end, just the borderline colors were changed for input so it shouldn't change the background. Let me know if the problem persists! 
Screen Shot 2021-10-31 at 1 39 30 PM

**Comment by knjk04** [comment]
@RivaD2 Does this show correctly on your end?

**Comment by RivaD2** [comment]
> @RivaD2 Does this show correctly on your end?

@knjk04 The delete account page does indeed 👍 , see below:
Screen Shot 2021-11-07 at 1 36 29 PM

**Comment by knjk04** [comment]
image

@RivaD2 and @grace-ko Thanks both, it looks to be a Firefox thing, it's fine on Chrome.

@grace-ko Are you able to reproduce this with Firefox?

**Comment by knjk04** [comment]
@grace-ko How are you getting on with this?

**Comment by knjk04** [comment]
@grace-ko Closing due to no reply

**Pull request closed without merging**
