### PR TITLE
781 refactor axios

### LINKED ISSUE #781: Refactor HttpClient to use Axios
Currently we have a customer built instance called HttpClient. We want to replace this with Axios for more robust API calls and easier maintenance.

- You should work out the `HttpClient.js` file and keep the same methods and exported instance. The consumers of HTTP client don't need to change.
- TypeScript linter may cause some bumps in the road

**Additional context**

- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**NOTES**

- Branch from the main branch and set main as the destination branch in your pull request
- See our [contributing guidelines](https://project-books.github.io/docs/development/contributing/) first 👍
- If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a).

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
## Summary of change

Refactor the `HttpClient.js` file to use Axios instead of Fetch 

## Related issue

Closes #781 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@gitaalekhyapaul Thanks for working on this! I've asked @RivaD2 to take a look at this when she's free

**Comment by gitaalekhyapaul** [comment]
Fixed in https://github.com/Project-Books/book-project/pull/792/commits/f722a12772a6610168ed88b657079fcef702849f and re-based :+1: 
CC: @RivaD2 @knjk04

**Comment by gitaalekhyapaul** [comment]
@RivaD2 It seems like I am not getting any errors when I run `yarn build`, since I am building the application before pushing my code. And I am not getting these errors in VSCode Intellisense as well.

**Comment by knjk04** [comment]
Request:

image

Response:

image

We are getting 200, but we're not navigating to the my-books page as before. If I do this manually, I see the following error due to 403 on the shelves endpoints:

image

**Comment by knjk04** [comment]
@gitaalekhyapaul Closing & unassigning due to no response (as per our contributing guidelines)

**Pull request closed without merging**
