### PR TITLE
Disable OSIV

### LINKED ISSUE #261: Consider disabling OSIV
Open Session in View (OSIV), represented by the spring property spring.jpa.open-in-view, is enabled by default.

From the Spring log: `spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning`.

It should be considered to disable it.

See: https://vladmihalcea.com/the-open-session-in-view-anti-pattern/ or https://www.baeldung.com/spring-open-session-in-view

### PR DESCRIPTION
**Pull request by dmitraver**
## Summary of change

Explicitly sets OSIV (open session in view) property to true (which is default value) to avoid warning during application startup. Its not clear what is the performance penalty when its enabled by default but at least the warning is gone.

## Related issue

Closes #261.

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
@dmitraver Thank you for working on this. I'll take a look over at the weekend when I get some more time as I want to look into OSIV

**Comment by dmitraver** [comment]
@knjk04 good, thanks. would you also mind adding **hacktoberfest-accepted** label to the PR, I think its required for new contributions.

**Comment by knjk04** [comment]
@dmitraver I don't know if you saw the discussion about this on Slack, but the `hacktoberfest-accepted` label is needed if the repository does not have the `hacktoberfest` topic (see https://hacktoberfest.digitalocean.com/hacktoberfest-update).

For good measure, I'll be adding the `hacktoberfest-accepted` label at some point this week to all hacktoberfest-related PRs

**Review by knjk04 — APPROVED** [review]
Thanks!

**Pull request merged**
