### PR TITLE
Issue 757: Blacklist tokens

### LINKED ISSUE #757: Invalidate JWT token after account deletion
Currently, JSON Web Tokens (JWTs) are used for passing authentication information. These tokens expire automatically, after a period of time.

Most requests need authorization information; otherwise, the requests are rejected (server returns 403 Forbidden response).

For example, if you want to list users, you will have to send valid authentication information.

The problem is that, after user account deletion, user JWT remains valid (until it expires) and can be used to make requests that normally should be rejected.

Steps to reproduce the issue:

1) Login using Postman (you may wish to create a new user account before, as you will have to delete it later)
https://github.com/Project-Books/book-project/wiki/Connecting-to-the-backend-via-Postman

2) Delete your own account
Using Postman, send a DELETE request to localhost:8080/api/user, having a raw body which contains email and password key/value pairs.

3) Make some requests where you use the JWT that belonged to the account you have just deleted.
Example: GET localhost:8080/api/user/users
Normally, this request should be rejected, but in practice you can successfully retrieve the result, because the JWT that is sent with the request is still valid.

**Additional context**
- Read our contributing guidelines first!
- We'll require you to discuss you implementation approach before being assigned to this
- Branch from `main` and set it as the destination branch in your pull request

### PR DESCRIPTION
**Pull request by mslowiak**
## Summary of change

Blacklisting tokens based on:
- existing account (if using token for not existing user - forbid)
- time of email change (if using previous token after password change - forbid)

## Related issue

Closes #757 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@mslowiak Thanks for working on this! I'll review this at some point this week

**Comment by knjk04** [comment]
@mslowiak I've taken a very look over this and noticed you're not creating a table to store blacklisted/already used tokens. Is there a particular reason for this?

**Comment by mslowiak** [comment]
> @mslowiak I've taken a very look over this and noticed you're not creating a table to store blacklisted/already used tokens. Is there a particular reason for this?

@knjk04  Yes, the initial thought was to save every token in a separate table...
However, this approach saves some time! If you think about tokens, there is a refresh token and an access token. 
To deactivate the token after logging out/ changing the password you would need to store the refresh token and access token. When refresh token is not a problem because it is usually long-lived, the access token is short lived, and saving it will hit db every time that refresh token is exchanged to the access token.

As a conclusion to that, I decided to keep the timestamp of the last password change date.
At every authenticated request we just query this table - if there is no user it means that he was deleted and the token is no longer valid. When the user exists we just validate if the issue date is after the last password change date.

**Comment by knjk04** [comment]
Hi @mslowiak, apologies for the delay. Something has come at home, but I'll review your comment as soon as I can

**Comment by mslowiak** [comment]
@knjk04

**Pull request closed without merging**
