### PR TITLE
Make tests parameterized

### LINKED ISSUE #479: Make password strength tests parameterized
In `UserTest.java` , we have the following three tests:

```java
void testWeakPasswordIsInvalid() {
    // given
    User user = userWithoutPassword().password("123456789")
                                     .build();
    // when
    tryToSaveInvalidUser(user);
    // then
    assertThat(userRepository.count()).isEqualTo(initialNumberOfUsers);
}
@Test
void testFairPasswordIsInvalid() {
    // given
    User user = userWithoutPassword().password("aPassWorD")
                                     .build();
    // when
    tryToSaveInvalidUser(user);
    // then
    assertThat(userRepository.count()).isEqualTo(initialNumberOfUsers);
}
@Test
void testGoodPasswordIsInvalid() {
    // given
    User user = userWithoutPassword().password("testPa$$123")
                                     .build();
    // when
    tryToSaveInvalidUser(user);
    // then
    assertThat(userRepository.count()).isEqualTo(initialNumberOfUsers);
}
```

**Context:**

'Weak', 'fair' and 'good' refer to password strengths (you can try this out by running the app). The problem here is that the shape of each of these three tests are the same: we construct an invalid user, try to save it and then assert that the number of users saved (userRepository.count()) has not changed (== initialNumberOfUsers).

**What we want:**

We want to eliminate the code duplication. As you may have noticed, the only thing that's changing is the password. We can combine these three tests into one and pass in as input strings that correspond to a weak, fair and good password. The way we do this in JUnit is by creating a parameterised test

### PR DESCRIPTION
**Pull request by SeonghoLee4**
## Summary of change

Added Parameterized JUnit test method in UserTest.java test.
Deleted the original 3 different testing methods.

## Related issue

Closes #479 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this. I've marked this as a draft so that you can fix the failing build

**Comment by knjk04** [comment]
Thanks for making the change. Could you please squash your second commit into the first? Once that's done, this should be ready to be merged in

**Comment by knjk04** [comment]
@SeonghoLee4 How are you getting on with this?

**Comment by knjk04** [comment]
@SeonghoLee4 How are you getting on with this? Did you manage to see my reply on Slack?

**Comment by SeonghoLee4** [comment]
> @SeonghoLee4 How are you getting on with this? Did you manage to see my reply on Slack?

**Comment by SeonghoLee4** [comment]
@knjk04 I just squashed the commits using git "rebase" command.

Could you check it out if the process is successfully completed?

**Review by knjk04 — APPROVED** [review]
All good, thanks

**Pull request merged**
