### PR TITLE
Forgot password modal 664

### LINKED ISSUE #664: Create forgot password modal
**Describe the solution you'd like**

Create a forgot password modal as shown in the screenshot below.

It should be centred in the middle of the screen and be responsive.

The modal component should be generic as it'll be used in other places

**Additional context**

image

### PR DESCRIPTION
**Pull request by RivaD2**
## Summary of change

**Current changes so far for feedback:**

**Modal.tsx**

- Created a `components` folder in the `/shared` directory along with `Modal.css and Modal.tsx`
- Brought in the `Modal` component from Material-UI which comes with props `open` and `onClose`

**ForgotPasswordModal.tsx**

- Created the above modal to ensure that the `<Modal />` in `Modal.tsx` is generic as it'll be used in other places
- Added various styles for text, and modal sizing etc.
- Imported in the `<Modal />` component and passed it the `open` prop and `onClose` prop
- Added `onClick` prop to Cancel button so it closes when clicked
- Takes in `Email` component and created `onEmailChanged` Class method 
  - Passed `onChange, isInvalid, and errorMessage` props to Email

**Login.tsx**

- Imported in ` <ForgotPasswordModal  />` and passed it the `open` prop which shows the modal when the value is true
- Added `showForgotPasswordModal` into state and set it to false
- Created `onForgotPassword()` method that holds the value for whether the modal is open or not
- Added `Button` below `create account` called `Forgot password` and passed it the `onClick()` prop that calls the `onForgotPassword()` method
- Added `onForgotPassWordModalClose()` method and `setState` to false

## Additional context

**I have some questions regarding the styling and the buttons:**

  - I went ahead and used the `Email` component we already have made so I hope that works for now :)
- For the password reset link, can you give me some additional details on how you want that to work? What endpoint I'm hitting etc...
Do we have two endpoints, one to initialize the “forgot password” process and one to change the password using the link generated in the first endpoint? 

https://user-images.githubusercontent.com/67027945/113517977-13edf080-9538-11eb-8175-e0b8aae0ac97.mov

## Related issue

Closes #664

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by RivaD2** [comment]
@knjk04 Can you take a look what I have thus far? I have some questions in the PR for you regarding how to proceed with the Email form :)

**Comment by knjk04** [comment]
Thanks for working on this! We don't have the endpoints yet. I'll take a look at this shortly

**Comment by knjk04** [comment]
I saw that you updated the video to use the reused email component. Is this ready for review?

**Comment by RivaD2** [comment]
Since we don't have endpoints yet, I suppose it is ready. I can mark it as
ready for review now.
Thank you for your assistance!

**Review by knjk04 — APPROVED** [review]
This is great! Thank you very much for working on this!

**Pull request merged**
