### PR TITLE
Email notification 779

### LINKED ISSUE #779: Send email confirmations
**Describe the solution you'd like**
Send an email confirmation when a user creates a new account, changes their password or deletes their account.

We should have a new Maven module for this email notification service.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

### PR DESCRIPTION
**Pull request by MartinSedlacko**
## Summary of change

Add EmailService module

## Related issue

Closes #779 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
Also, could you please look into why the build is failing?

**Comment by knjk04** [comment]
@MartinSedlacko Thanks for bringing the tests back and making the other changes. I noticed your commits aren't showing properly (see https://project-books.github.io/docs/development/contributing/#ensure-your-email-address-on-your-commits-are-correct). Could you please fix this?

**Comment by MartinSedlacko** [comment]
@knjk04 I have fixed my commits. Is it showing right, now?

**Comment by knjk04** [comment]
@MartinSedlacko Thanks they're showing correctly

**Review by knjk04 — CHANGES_REQUESTED** [review]
Thanks for this. I've noticed there are 260 files affected and for many files, the only thing that has changed is the order of the import statements. To make this easier to review, would it be possible to undo the reordering of imports?

**Comment by MartinSedlacko** [comment]
@knjk04 I have reordered imports.

**Comment by knjk04** [comment]
@MartinSedlacko Apologies for the delay in getting back to you. How can I test this out?

**Comment by MartinSedlacko** [comment]
@knjk04 Hello, configure email.properties(spring.mail.username, spring.mail.password) and then, when you create a new account, change password or delete an account, an email will be sent.

**Comment by knjk04** [comment]
@MartinSedlacko So sorry for the delay. I'll get back to this shortly

**Review by knjk04 — APPROVED** [review]
Thanks a lot for adding the email service, this works great!

**Pull request merged**
