### PR TITLE
Adding Book Progress states

### LINKED ISSUE #198: Split Book entity
**Context**

The `Book` entity currently includes the following fields:

>  // For books that have been read
    private RatingScale rating;
    private LocalDate dateStartedReading;
    private LocalDate dateFinishedReading;
    private String bookReview;

The comment indicates that those four fields are only applicable to books that have been read, and not just any book (e.g. a book that is yet to be read).

**What needs to be done**

The `Book` entity could be split into a new class that inherits from `Book` called `ReadBook` with those fields.

### PR DESCRIPTION
**Pull request by Hassan-Elseoudy**
## Summary of change

So main change that I added a new feature, Book Progress .. A New table that connects between Users and Book.
Book Progress has a state of 3 (To be read, In Progress and Completed), A book progress will be defined by state and other parameters like Start Date, End Date, number of pages read, my ratings and my review.

I tried to decouple the book from its life cycle that is related to the user. 
Also Added some Test, and a Minor change for MAX_PAGE to be handled with `@Range` annotation except `@Max`.

Also, please note that `pages` for each book is `Required` for the book progress, A system can track User's progress in reading book by checking user's read pages and book's pages.

I left all of those stuff dependent, I didn't change anything till you decide to inject those class in your actual services.

## Additional context

No UI Changes, only

## Related issue

Closes #198

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset.  (**I may be missing this, sorry :)** )

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

### CODE REVIEW

**Comment by Hassan-Elseoudy** [comment]
I also moved boot entity, genere and progress to a new package to keep things more structured.

**Comment by Hassan-Elseoudy** [comment]
I checked the conflicts files, All of them are because of the package name, you can either accept my new package or not.
It'll make no difference but for more structured view.

Have a nice night @knjk04

**Comment by Hassan-Elseoudy** [comment]
Anyway, I decided to get back to old structure. :)) 
Checked the report, Hopefully everything is clear and good now.

**Comment by knjk04** [comment]
@Hassan-Elseoudy Thanks for working on this. 

From a quick look, here a few thoughts.

> Book Progress has a state of 3 (To be read, In Progress and Completed),

What about the 'did not finish' state?

Also, I noticed there are lots of style guide violations (missing copyright notices, lines that exceed our 100 character column limit, wildcard imports, using JUnit assertions instead of AssertJ, missing given/when/then comments, etc.). Could you please review our style guide again and make the necessary changes? 

We haven't had a chance to conduct a full code review yet, but as mentioned recently in our Slack workspace, adhering to our style guide will speed up the time it takes to get your PR merged in.

**Comment by Hassan-Elseoudy** [comment]
IMO, `did not finish` is equal to `In progress` It is already covered.
I'll work with style guiding.

**Comment by knjk04** [comment]
> IMO, did not finish is equal to In progress It is already covered.

We distinguish between 'currently reading' and 'did not finish'. With 'did not finish', there's an additional attribute (and there may be more in the future) -- pages read

**Comment by Hassan-Elseoudy** [comment]
Isn't pages read an indicator that the book is also in progress? I didn't get it yet
I'm pretty sure that all conditions apply to `didn't finish` are applied to `In progress`
Any way using `Builder` Pattern, We can add new attributes any time :+1:

**Comment by Hassan-Elseoudy** [comment]
Ready for review :+1: @knjk04

**Comment by knjk04** [comment]
> includes the issue number at the end, e.g. test-reading-goal-123

The above is from our PR checklist and we also mention this in our contributing document.

I noticed that your branch name does not include the issue number. Could you please rename your branch (`git branch -m <new-branch-name>) and then create a new pull request for this (you can copy the completed template here in the new one)?

**Pull request closed without merging**
