### PR TITLE
Make app bar light by default

### LINKED ISSUE #625: Implement light app bar
**Describe the solution you'd like**
- Add a material UI switch that lets a user toggle dark mode (by default, we want light mode)
image

- Add a light app bar with a shadow. The logo, material UI icons and text should be white in light mode
image

### PR DESCRIPTION
**Pull request by RivaD2**
## Added Material-UI switch so user can toggle dark mode (default theme is set to light mode)

**Switch:**
- [x] Created `Switch.tsx` to extract Material-UI Switch logic out of `Settings.tsx`/to increase reusability of Switch
- [x] Dropped Material-Ui Switch Component into `Settings.tsx`
- [x] I wrapped the `Switch` and `CssBaseline` inside the `MuiThemeProvider` from Material-UI (CssBaseline needs to be inside MuiThemeProvider to ensure that the body background changes as modes switch)
- [x]  Added additional CSS styles to bring Switch inline with toggle text 

**Styling:**
- [x] Removed all previous set colors  in `NavBar.css` and `Settings.css` as this is now set by Material-Ui darkMode and lightMode palette types of 'dark' and 'light' .
    - Added `navClass` variable in `NavBar.tsx` to set CSS styles when mode is 'light' or 'dark' (variable holds logic of showing the box shadow for light mode, and black navBar background color when in different modes)
    
**Theme:**
- [x] Created `lightTheme` and `darkTheme`. Combined the `lightTheme` with the existing theme in `Theme.tsx`. `darkTheme` was created with `CreateMuiTheme`  and added into `Theme.tsx` also.
  - Created the method `toggleTheme()` and passed it in as a prop to the `routes.Settings` Route in `App.tsx`
   - I left `App.tsx` as a Function component and used the `useState` hook to set the theme in the State of `App.tsx`. (I am happy to refactor this as a Class-based component if this is preferred)
   -  On `App.tsx` I wrapped all Routes and components inside the `ThemeProvider` 
   - Passed theme/setTheme callback props  to `<Settings />` in `App.tsx` using `render()`  prop since `component` prop doesn't give me a way of passing additional props to the `<Settings />` component.
 - [x] Conditionally rendered dark logo based off `theme.palette.type` in `NavBar.tsx`
 -  [x] Added `dark-logo.png` to `media/logo` folder 
   
  
## Additional context

**Toggling of themes Updated:**

https://user-images.githubusercontent.com/67027945/109846288-e3e2c300-7c02-11eb-8dfa-1acbd54191b4.mov

## Related issue

Closes #625

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [] Ensure code changes pass all tests (no testing done for this issue)

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this! This is coming along nicely and is almost there! 

In dark mode, would it be possible to only change the app bar and leave the content area white? 

Also, would it be possible to have the toggle in line with the 'Enable dark mode' text?

Here's a black image:
logo-two-lines-black@1x

**Comment by RivaD2** [comment]
Hello Karan,

 I'm glad to help!

This issue is much harder than I originally thought :) Figuring out dark
mode and where to store state etc. was a bit tricky for me (and the
Material-UI docs can be tricky as well).

I'm happy to make the requested adjustments, no problem!

**Comment by knjk04** [comment]
I can see you've put a lot of effort in and you've done well so far! If you do need help with anything, feel free to ask and I can take a look

Also, thanks for the video! That helped a lot (I didn't need to clone it).

**Comment by knjk04** [comment]
> Note: When using Material-Ui dark mode, background color is assigned dark mode palette type from Material-UI which is why it is dark as seen in video vs light when dark mode is chosen. If we want background color to be white in dark mode, I am happy to try and apply an override

I missed this before, but yes, can we override this?

**Comment by RivaD2** [comment]
@knjk04 Today I will start on the following requested changes:
      - Add in black logo for light mode
      - Make content area  white in dark mode, (only App bar will take in changes)
      - Adjust level of hardness/shadow on border of App bar (more gray, less black)
      - Bring Toggle inline with dark mode text

**Comment by RivaD2** [comment]
I made the requested changes and added in an updated movie to the PR to show all changes made. 

I do have one last question regarding something I just noticed. When the user toggles to dark mode, what should the text say near the toggle switch? Do you want it to say, "Enable light mode?" or just leave just the toggle by itself with no text?

**Comment by knjk04** [comment]
Thanks! 

"Enable dark mode" is good.

I'll review this shortly

**Comment by knjk04** [comment]
Thanks a lot for working on this!

image

The button and primary theme are blue, but we changed this to black (see #627 for what this page should look like). Perhaps you don't have those changes in your branch?

**Comment by RivaD2** [comment]
@knjk04, thank you for the reminder on the button colors. I will go ahead and make that change in the next couple of hours. 
  It looks like I haven't received those changes to primary color on Login. I will bring my branch level to 0.2.0 again and see what is happening there.

I will reach back out when it is completed :)

**Comment by RivaD2** [comment]
> ## Added Material-UI switch so user can toggle dark mode (default theme is set to light mode)
> * [x]  I added Material-Ui Switch Component into `Settings.tsx`
> * [x]  I wrapped the `Switch` and `CssBaseline` inside the `MuiThemeProvider` from Material-UI (CssBaseline needs to be inside MuiThemeProvider to ensure that the body background changes as modes switch)
> * [x]  Removed all previous set colors  in `NavBar.css` and `Settings.css` as this is now set by Material-Ui darkMode and lightMode palette types of 'dark' and 'light' .
>   
>   * Added `navClass` variable in `NavBar.tsx` to set CSS styles when mode is 'light' or 'dark' (variable holds logic of showing the box shadow for light mode, and black navBar background color when in different modes)
> * [x]  I created two themes using `CreateMuiTheme` (lightTheme and darkTheme in `App.tsx`)(these theme types are built in to Material-UI) and give us quick access to dark theme palette and light theme palette from Material-UI
>   
>   * Created the method `toggleTheme()` and passed it in as a prop to the `routes.Settings` Route in `App.tsx`
>   * I left `App.tsx` as a Function component and used the `useState` hook to set the theme in the State of `App.tsx`. (I am happy to refactor this as a Class-based component if this is preferred)
>   * On `App.tsx` I wrapped all Routes and components inside the `ThemeProvider`
>   * Passed theme/setTheme callback props  to `<Settings />` in `App.tsx` using `render()`  prop since `component` prop doesn't give me a way of passing additional props to the `<Settings />` component.
> * [x]  Conditionally rendered dark logo based off `theme.palette.type` in `NavBar.tsx`
>   
>   * Added `dark-logo.png` to `media/logo` folder
>   * Added additional CSS styles to bring Switch inline with toggle text
> 
> ## Additional context
> **Toggling of themes Updated:**
> 
>  toggleSwitch.mov 
> ## Related issue
> Closes #625
> 
> ## Pull request checklist
> Please keep this checklist in & ensure you have done the following:
> 
> * [x]  Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
>   
>   * [x]  Ensure that you were first assigned to a relevant issue before creating this pull request
>   * [] Ensure code changes pass all tests (no testing done for this issue)
> * [x]  Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset.
> * [x]  Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
>   
>   * [x]  Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)
> * [x]  Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`
> * [x]  Set this pull request to 'draft' if you are still working on it
> * [x]  Resolved any merge conflicts
> 
> For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.
> 
> If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

**Comment by RivaD2** [comment]
@knjk04 Alright, I am in the process of bringing my branch level with 0.2.0 and getting my lightAppBar branch merged into origin.
  The changes I made were:
         - Extracted Switch logic into it's own component (as there was too much material UI code in the Settings component and to increase reusability of Switch in Application)
         - Still dropped in Switch component into `Settings.tsx` with props to toggle theme
        - The Switch is made up of various pieces (thumb, track, base etc.) were all made black in `Switch.tsx`. 
Questions: I know you said that the Switch should be black but the track itself, when the Switch is clicked on or off, I left grey. I know sometimes with switches, colors are used to let the user know when the switch is on or off. Does the way I did it work out ok?

Thank you!

**Comment by knjk04** [comment]
Thanks for this! The toggle works great!

image

Does the login screen still look like this for you?

**Comment by RivaD2** [comment]
Hello,
  I am happy you like the toggle :)

 I just checked the Login page and it does still look like that. I am not
sure why as my upstream/0.2.0 /origin/0.2.0/ 0.2.0 are all even with one
another. My lightAppBar-625 branch is showing ahead of the upstream 0.2.0/
origin 0.2.0 and 0.2.0

I must be missing something.. Were changes made to Login for black theme on
the 0.2.0 as well? I am trying to figure out if I need to do another
fetch/pull. Thank you for your help!

**Comment by RivaD2** [comment]
Wait! Hello again.
  I just refreshed after starting up app, and it is good to go! My login
does not have the purple button and theme is black. Whew!

**Comment by knjk04** [comment]
Merging sounds good, thanks!

**Comment by RivaD2** [comment]
@knjk04 , I merged 0.2.0 into my branch. Here is what the 0.2.0 branch and my branch look like when checked out (Hopefully this will help you to see what's going on a bit better):

Screen Shot 2021-03-05 at 8 21 06 AM

Screen Shot 2021-03-05 at 8 21 25 AM

For some reason, when I am on my lightAppBar branch, I still have the old login with purple button.

**Comment by RivaD2** [comment]
@knjk04 Alrighty, so, I figured out that I wasn't experiencing a merge issue, whew! The Login page looks good now for me(black button with border radius etc.).

What happened was that my light and dark themes didn't specify the primary color set in `theme.tsx`. So, my themes were using the default primary color, which was purple, and were overriding the themes made for Login.

 So I had to move the `lightTheme` and `darkTheme` into `theme.tsx` with the others, and then merge my lightTheme with the existing theme.   his way, the light and dark themes can be in with the other page theming.
I believe we are definitely good now. Thank you for all of your help :)

**Comment by knjk04** [comment]
I'm glad to hear you figured it out!

**Review by knjk04 — APPROVED** [review]
Thank you very much for working on this!!

**Comment by RivaD2** [comment]
@knjk04 thank you, I'm happy to help!

**Pull request merged**
