### PR TITLE
hide/show password toggle

### LINKED ISSUE #560: Add show/hide password toggle
**Describe the solution you'd like**
Add an input adornment that's an icon to toggle showing and hiding the password. We need to use the icon in Material UI

**Additional context**
See [input adornments](https://material-ui.com/components/text-fields/#input-adornments)

### PR DESCRIPTION
**Pull request by RivaD2**
## Summary of change

- In the `Password.tsx` component, I added an additional `prop` on the `<OutlinedInput>` of: 
`type={showPassword ? 'text' : 'password'}`
- I then changed the `InputAdornment` component as follows:
```
<InputAdornment position="end">
              <IconButton
                aria-label="toggle password visibility"
                size="small"
                onClick={handlePasswordToggle}
              >
                {showPassword ? <Visibility /> : <VisibilityOff />}
              </IconButton>
            </InputAdornment>
```
- Added the `useState` hook as I was working in a function component and added the `handlePasswordToggle()` method (wasn't sure if I should just change function component to Class based component as it looks like the frontend is utilizing both).

## Additional context

hidePassword

showPassword

## Related issue

Closes #560

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests **I did not write test for this issue**

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks a lot for this, Riva! I'll review this shortly, but it looks fine from a quick glance.

Could you please bring your branch up-to-date with `0.2.0`? I'd recommend rebasing

**Review by knjk04 — APPROVED** [review]
Thanks for working on this!

**Comment by RivaD2** [comment]
@knjk04 Alrighty, I didn't do a rebase but I did a soft reset. So, my branch is now up to date with 0.2.0. Can you take one last look and let me know if we are good to merge? Thank you :)

**Comment by knjk04** [comment]
That's great, thanks

**Comment by RivaD2** [comment]
@knjk04 You are most welcome! Thank you for the extra info on being a contributor as well. I figured that I had to wait until all was merged into master, so that's cool! 
I am watching the repo and look forward to working on more React issues :)

**Comment by knjk04** [comment]
Great! I'll be making lots more as this release is all about getting to what we had in `0.1.0` but with a better design! I'm not sure how you're finding the work so far, but I suspect things will get more challenging as well as we connect to the backend and try out more advanced React things

**Pull request merged**
