### PR TITLE
Create export account data endpoint

### LINKED ISSUE #696: Create export account data endpoint
**Describe the solution you'd like**
Create a new controller and endpoint to export a user's book data:
- All of the books in their predefined and custom shelves
- All tags, publishers, etc.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

This needs to be thoroughly tested.

### PR DESCRIPTION
**Pull request by jwlai**
## Summary of change

* Added ExportService.java
* Added ExportController.java
* Added UserCreatedShelfSerializer.java
* Added PredefinedShelfSerializer.java

## Related issue

Closes #696 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [ ] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
- [x] Ensure that you were first assigned to a relevant issue before creating this pull request
- [x] Ensure code changes pass all tests
- [ ] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by jwlai** [comment]
@knjk04 Hi, I wanted to start the progress for this- the main change I'm concerned with is the following in Book.java.

`@JsonIgnoreProperties(value = {"id", "predefinedShelf", "userCreatedShelf"})`

Also because I serialized a HashMap... See [here](https://gist.github.com/jwlai/140f2603b258d1257950e3871a7ccb62)

**Comment by knjk04** [comment]
Thanks for working on this. Sorry, how come you're concerned with that line?

**Comment by jwlai** [comment]
I was just not sure if there's any other JSON Serialization cascading effects that would be affected- If it's OK I will clean the pull up and check the merge!

**Comment by knjk04** [comment]
Closed due to no response

**Pull request closed without merging**
