### PR TITLE
Password length limited to 128 characters when registering an account.

### LINKED ISSUE #281: Set an upper limit to maximum user password length
The password strength measuring added to resolve issue https://github.com/knjk04/book-project/issues/262 slows down considerably for very long passwords.

Measuring a 128 character password takes ~500ms.
Measuring a 512 character password takes ~3000ms

This could be used for denial of service attacks when using extremely long passwords.

**to reproduce:**
1. click on "register user"
2. fill out password field

The password length should be limited to a maximum of 100-128 characters.

### PR DESCRIPTION
**Pull request by MikeLowrie**
## Summary of change

The Password and Confirm Password fields on making a new account now limit the number of characters to 128.

## Related issue

Closes #281

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for creating the PR, @MikeLowrie!

image

Instead of showing a server error, it would be better if we could explicitly tell the user that the problem is that they entered more than 128 characters. Could you please add validator in `RegistrationForm` that checks for this?

Also, if it helps, this is the test string I was using:
RtMxPlmjhfWn8GLe44nnyBWVvOGlTK0IeWmah80GdXh2M6bu9OkWThdDU3uVrhaDw8YMhWg5ed2CdCy67KNhSq9SKBU7t9xQddW2h8B50nDa6u0QjIPwVA6fSrdNuXqF5

As ever, feel free to get in touch with us over Slack if you need a hand with this

**Review by knjk04 — CHANGES_REQUESTED** [review]
Thanks for creating the PR, @MikeLowrie!

image

Instead of showing a server error, it would be better if we could explicitly tell the user that the problem is that they entered more than 128 characters. Could you please add validator in `RegistrationForm` that checks for this?

Also, if it helps, this is the test string I was using:
RtMxPlmjhfWn8GLe44nnyBWVvOGlTK0IeWmah80GdXh2M6bu9OkWThdDU3uVrhaDw8YMhWg5ed2CdCy67KNhSq9SKBU7t9xQddW2h8B50nDa6u0QjIPwVA6fSrdNuXqF5

As ever, feel free to get in touch with us over Slack if you need a hand with this

**Comment by MikeLowrie** [comment]
I've pushed forward what I believe will work for warning users of password length violation specifically, but after rebuilding my environment I found that Docker isn't configured correctly so I did not have a chance to test it. Since I haven't tested the code myself, I'm leaving this as draft but testing this should be pretty straightforward.

**Comment by knjk04** [comment]
Thanks, I'll check this out. 

I noticed that the diff is unnecessarily large. It seems to include other commits. Would it be possible to resolve this (or get in touch over Slack and we can help)?

**Comment by MikeLowrie** [comment]
I'll DM you on Slack to discuss this further.

**Review by knjk04 — APPROVED** [review]
Thanks for working on this & addressing the changes! I've extracted 128 to a constant to prevent reusing a magic number, and I've also added an accompanying test

**Pull request merged**
