### PR TITLE
Test added to check if saved book can be found

### LINKED ISSUE #365: Test whether a saved book can be found
Test whether a saved book (a `Book` needs to first be saved) can be found using `findById()`.

If you run into issues and get stuck (e.g. lazy initialization exceptions), feel free to get in touch with us over Slack)

**Additional context**

The following can be removed when this test is in place:

```java
        List<Book> books = bookRepository.findAll();
        if (books.contains(book)) {
            LOGGER.log(Level.SEVERE, book.getTitle() + " not deleted");
        } else {
            LOGGER.log(Level.INFO, book.getTitle() + " deleted. Book repository size = " +
                    bookRepository.count());
        }
```

### PR DESCRIPTION
**Pull request by Ruchika8**
## Summary of change

Test added to check if saved book can be found. Used transactional to prevent usage of proxy by getOne

## Related issue

Closes #365

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [X] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [X] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [X] Ensure code changes pass all tests

- [X] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [X] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [X] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [X] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by Ruchika8** [comment]
> As is stands, you won't show up as a contributor. One possible reason for this is because your email address attached to your commits is/are not the same as those associated with your GitHub account.
> 
> In line with the ['Ensure your email address on your commits are correct'](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#ensure-your-email-address-on-your-commits-are-correct) section our style guide, you'll need to fix this. Instructions on how to do so can be found [here](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#rewriting-pushed-commits-with-a-different-email-address)
> 
> For more information, see https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile
> 
> I'll mark this PR as a draft. Feel free to request a review when you have fixed this.
> 
> If you need a hand with this, let us know over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw).

oh I apologize! that skipped my mind as I used my work id

**Comment by knjk04** [comment]
@Ruchika8 No problem, thanks for resolving this. I'll mark this PR as a draft while you fill in the rest of the PR description. Once you're ready for a review, feel free to press the 'ready for review' button

**Comment by knjk04** [comment]
@Ruchika8 Unfortunately, I think you took the wrong approach to issue #365 here.

Issue #365 requires a JUnit test. We want to first save a book and then check whether it can be found using `findById()`

**Review by knjk04 — CHANGES_REQUESTED** [review]
@Ruchika8 Unfortunately, I think you took the wrong approach to issue #365 here.

Issue #365 requires a JUnit test. We want to first save a book and then check whether it can be found using `findById()`

**Comment by Ruchika8** [comment]
> @Ruchika8 Unfortunately, I think you took the wrong approach to issue #365 here.
> 
> Issue #365 requires a JUnit test. We want to first save a book and then check whether it can be found using `findById()`.
> 
> Could you please see to this? If anything is unclear, feel free to follow up

Oh now I understand! I felt it required a junit at first but got confused by some additional context mentioned in the description of the issue. Will correct it asap

**Review by knjk04 — APPROVED** [review]
Thanks for working on this!

**Comment by knjk04** [comment]
I've renamed the test method to better reflect with our naming scheme. (It may seem strange right now, but once we've merged in the PR that is dealing with adding display names, it should be read as "BookService should findSavedBook")

**Pull request merged**
