### PR TITLE
Issue 775: Book PATCH

### LINKED ISSUE #775: Create a JSON patch method in the book controller
**Describe the solution you'd like**
In the [update ](https://github.com/Project-Books/book-project/blob/main/backend/src/main/java/com/karankumar/bookproject/backend/controller/BookController.java#L131)method of our BookController, use JSON patch to determine what attribute to change.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

### PR DESCRIPTION
**Pull request by mslowiak**
## Summary of change

Add implementation of PATCH method for the book.

## Related issue

Closes #775

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
@mslowiak Thanks for creating this PR! Are you still working on this or is this ready for a review?

**Comment by mslowiak** [comment]
@knjk04 It is ready for a review 👍

**Review by knjk04 — CHANGES_REQUESTED** [review]
Thanks for working on this! I've tested this and it works fine.

While this is fine, it may be simpler to use JSON patch (e.g. see https://www.baeldung.com/spring-rest-json-patch). We only need the add, remove and replace options. Could you update this PR to use JSON patch?

**Comment by mslowiak** [comment]
@knjk04 I think the current solution meets the expectation and if we want to adjust that behaviour (in the whole application) it will require more effort and it is more likely new issue rather than modification in this one.

Let Me know your thoughts

**Comment by knjk04** [comment]
@mslowiak This issue was only for the book controller (we're not using patch anywhere else right now) and specifically for implementing JSON patch. JSON patch has the advantage of maintaining less code on our part.

However, I agree that this is fine and it works well for now. Thanks!

**Review by knjk04 — APPROVED** [review]

**Pull request merged**
