### PR TITLE
date issue

### PR DESCRIPTION
**Pull request by bharatbahl**
## Summary of change

Have cast one operand to float and then added a test case to check the method.

## Related issue

Closes #[391]

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [X] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [X] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [X] Ensure code changes pass all tests

- [X] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [X] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [X] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [Done ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
Hi @bharatbahl,

Thanks for working on this. 

> [ Done ] Ensure that you were first assigned to a relevant issue before creating this pull request

Please note for the future that our process is to first request to be assigned to an issue. This helps us ensure various things, such as reducing the chances of duplicated work. I also noticed that you marked that you did this in the pull request, but did not.

Before we proceed, could you please request to be assigned on the issue?

**Comment by bharatbahl** [comment]
Hi @knjk04,
I have requested to be assigned to this issue on the Issue page. (Convert integer division to floating point division #391)

**Comment by knjk04** [comment]
Thanks for requesting. Now, others can see that this issue is taken.

> - [Done ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

I noticed that you're trying to merge in from the master branch on your fork. Could you please branch off master and create a descriptive branch name that includes the issue number (391)?

**Comment by bharatbahl** [comment]
Okay thanks for guiding. Will do :)

**Comment by knjk04** [comment]
Before proceeding, I'd recommend reviewing our [contributing guidelines](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md) and [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md).

**Pull request closed without merging**
