### PR TITLE
Frontend mui outline label

### LINKED ISSUE #864: Material UI text field text overlaps with text field border
**Describe the bug**

image

The text for a text field overlaps the text field border when you click on it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://localhost:3000/
2. Click on the username or password text field
3. See the error

**Expected behaviour**

image

The text should not overlap the text field border, as with the above image.

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

### PR DESCRIPTION
**Pull request by Krishpandya682**
## Summary of change

Imported mui library to make the outlined mui TextField not overlap with

## Additional context
Before :-
148653312-7fa97766-a9b6-4ba4-a792-fef83b494de0

After:-
Screenshot (849)

## Related issue

Closes #864 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [ ] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [ ] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [ ] Ensure code changes pass all tests

- [ ] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [ ] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Review by knjk04 — CHANGES_REQUESTED** [review]
@Krishpandya682 Thanks for working on this! Could you please change the accent colour for the text fields back to black (now blue)?

**Comment by Krishpandya682** [comment]
Hi @knjk04,
The change in color is a part of the validation of the input fields and I am not sure if they can be changed.

https://user-images.githubusercontent.com/76144309/149004400-92212747-7411-4525-b949-44efea537f1a.mp4

**Comment by knjk04** [comment]
@Krishpandya682 How are you getting on with this?

**Comment by knjk04** [comment]
@Krishpandya682 Closing due to no response (as per our contributing guidelines)

**Pull request closed without merging**
