### PR TITLE
Export user book data

### LINKED ISSUE #696: Create export account data endpoint
**Describe the solution you'd like**
Create a new controller and endpoint to export a user's book data:
- All of the books in their predefined and custom shelves
- All tags, publishers, etc.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

This needs to be thoroughly tested.

### PR DESCRIPTION
**Pull request by olusolaa**
## Summary of change

Created current user's book export service
Exposed export service endpoint
Added UserCreatedShelfSerializer.java
Added PredefinedShelfSerializer.java

JSON is outputed this way.
----
```yaml
{
    "userPredefinedShelf": [
        {
            "shelfName": "Did not finish",
            "books": [
                {
                    "title": "Stardust",
                    "numberOfPages": 489,
                    "pagesRead": 831,
                    "bookGenre": [
                        "HORROR"
                    ],
                    "bookFormat": null,
                    "seriesPosition": 9,
                    "edition": null,
                    "bookRecommendedBy": "John",
                    "isbn": null,
                    "yearOfPublication": 1980,
                    "author": {
                        "fullName": "J.K. Rowling"
                    },
                    "tags": [
                        {
                            "name": "Adventure"
                        }
                    ],
                    "publishers": [
                        {
                            "name": "Scholastic Corporation"
                        }
                    ],
                    "rating": "NO_RATING",
                    "dateStartedReading": "2021-09-25",
                    "dateFinishedReading": null,
                    "bookReview": "Must Read Book. Really Enjoyed it"
                },
```

## Related issue

Closes #696

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by olusolaa** [comment]
@knjk04 it trows a json exception because  "predefinedShelf", and "userCreatedShelf"  was not added to the @JsonIgnoreProperties in the book model.

**Comment by knjk04** [comment]
@olusolaa Are you able to find a way around this?

**Comment by olusolaa** [comment]
@knjk04, have you noticed the changes I made on the book model? Is it you don't want us to go that route, because, with those changes, it's working fine at my end.

**Comment by olusolaa** [comment]
Please, let me know if you don't want us to ignore the predefinedshelf and usercreatedshelf from the json output of each book.

**Comment by olusolaa** [comment]
@knjk04 I'm awaiting your response

**Comment by knjk04** [comment]
@olusolaa Thanks for your reply. I'll take a look at this over the weekend

**Comment by knjk04** [comment]
@olusolaa How are you getting on with this?

**Comment by knjk04** [comment]
@olusolaa Closing due to no response

**Pull request closed without merging**
