### PR TITLE
Create shelf carousel component #656

### LINKED ISSUE #656: Create Shelf carousel component
**Describe the solution you'd like**
Create a new shelf carousel component to go on the 'my books' page. It should have the following:
- Name of the shelf
- A 'VIEW ALL' link next to the shelf name
- A white shelf with a shadow
- Equally sized and spaced apart slots for books (a simple rectangle will suffice for now as placeholders). There should be at most six slots
- An 'Add book' slot at the end of the shelf

This should be a reusable component as it will also be used on other pages.

**Additional context**

image

The shelf carousel should look like the above image

image

The image above represents the placement of the shelves

### PR DESCRIPTION
**Pull request by ofvoler**
## Summary of change

Add a Shelf Carousel component that will primarily be used for the My Books page.

## Additional context

shelf carousel

## Related issue

Closes #656 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by ofvoler** [comment]
Hi Karan! I was hoping you could take a look at this and let me know how you think it's going. I have two main things I would appreciate feedback on:

1. The design isn't responsive to a smaller browser size. How should it be formatted in that case? Have fewer books, make everything smaller, or something else?
2. I have generated one static version of the shelf. Should I create a GraphQL query in the My Books file to get all of the books on one shelf and pass them as props? 

Thanks!

**Comment by knjk04** [comment]
Hi Olivia, thanks for working on this!

> The design isn't responsive to a smaller browser size. How should it be formatted in that case? Have fewer books, make everything smaller, or something else?

What's the fewest number of books on a shelf we can show on the smallest, fairly popular mobile device?

> I have generated one static version of the shelf. Should I create a GraphQL query in the My Books file to get all of the books on one shelf and pass them as props?

Once Kate has finished with the #636, we'll make a call to the REST endpoint (GraphQL is for the Books API only).

**Comment by ofvoler** [comment]
So for now, do you think I should create the shelf books as a separate component (i.e. not in the ShelfCarousel component) so that they can be passed to ShelfCarousel as props when we make the call to the endpoint? Or should I not worry about that right now? 

> What's the fewest number of books on a shelf we can show on the smallest, fairly popular mobile device?

I wonder if we could show 5-6 books, smaller, but in 2-3 rows of shelf instead of one (I'll also have to see if I _can_ do that). What do you think? Do you have better ideas?

**Comment by knjk04** [comment]
> So for now, do you think I should create the shelf books as a separate component (i.e. not in the ShelfCarousel component) so that they can be passed to ShelfCarousel as props when we make the call to the endpoint? Or should I not worry about that right now?

Don't worry about that for now. We'll be in a better position to figure out how best to implement this once we're there

> I wonder if we could show 5-6 books, smaller, but in 2-3 rows of shelf instead of one (I'll also have to see if I can do that). What do you think? Do you have better ideas?

Not sure if they're better, but here's a couple of ideas:

- Only show the minimum number of books we can (e.g. 2 or 3). We can have arrow chevrons that users can look to see more. and/or a 'see all' button/link
- No shelf view for small screens

**Comment by ofvoler** [comment]
I think we should implement a combination of your two ideas. For smaller desktops (tablets, smaller desktops), we decrease the size of the books to fit a few more, and show fewer depending on how big the screen is. I've added two breakpoints and implemented the size change, but I think decreasing the number of books will have to be implemented when we populate the shelves (I temporarily deleted some books to show how it should look).

small desktop
tablet


And as far as mobile, I agree that we shouldn't allow shelf view. We'll definitely have to adjust the nav bar as well, but I guess both of those things can come later—that's more of a UX thing anyway. I attached a screenshot of how it looks on a mobile screen right now.

mobile

Knowing that we can't implement shelf population right now, I don't think there's much else I can do right now, unless there are some more visual things you'd like me to change. Let me know!

**Comment by knjk04** [comment]
Thanks for this. It looks like we had an old screenshot on the issue (I'll update that). 

image

Could we have the 'add book' slot look like the above (white background with blue text)?

**Comment by ofvoler** [comment]
Sure thing! Since you made commits, do I need to pull from upstream onto my branch for it to merge correctly?

**Comment by knjk04** [comment]
@ofvoler Thanks! Sorry, I should have changed the image earlier.

> do I need to pull from upstream onto my local branch for it to merge correctly?

Almost right. If you run `git pull origin create-shelf-carousel-656`, then that should be fine (I committed to your fork, not upstream).

**Review by knjk04 — APPROVED** [review]
Thanks a lot!

**Pull request merged**
