### PR TITLE
Create reading goal section #666

### LINKED ISSUE #666: Create reading goal section
**Describe the solution you'd like**
image

Create the reading goal section as shown above.

**Additional context**

image

The above screenshot shows what it should look like within the context of the entire page (the completed goals section is not yet there)

### PR DESCRIPTION
**Pull request by ofvoler**
## Summary of change

Add content to the reading goal page (page header and box with description 'no goal set')
Add styling consistent with other pages

I can see this getting messy as we add more files. 
- Is there a global css file, or should we create one so that the format of all page headers/margins remain consistent?
- Could we create a layout component that has the nav bar, sets automatic margins, and styles page headers?

## Additional context

reading goal

## Related issue

Closes #666 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us by creating a [Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) on GitHub or ask on the #help channel in our Slack workspace

### CODE REVIEW

**Comment by knjk04** [comment]
> Is there a global css file, or should we create one so that the format of all page headers/margins remain consistent?

Yes, see [index.css](https://github.com/ofvoler/book-project/blob/create-reading-goal-666/frontend/src/index.css)

> Could we create a layout component that has the nav bar, sets automatic margins, and styles page headers?

Sure! I can create a separate issue for this or you implement the component here. What's best?

**Comment by ofvoler** [comment]
I think separately is probably best. Then I can go implement it in the files and it won't look like it's all part of this issue, since they're pretty unrelated.

**Comment by knjk04** [comment]
Sure, could you create a new issue for it?

**Comment by knjk04** [comment]
Sure, could you create a new issue for it?

**Comment by ofvoler** [comment]
Okay, I just created it as issue #674

**Review by knjk04 — APPROVED** [review]
Thanks for working on this!

**Pull request merged**
