### PR TITLE
Connect the login view to the backend

### LINKED ISSUE #608: Connect the login view to the backend
**Describe the solution you'd like**
Send a GET request to the server when the user tries to the login with the values passed into the email address and password fields.

If the server does not authorise the client, show an error message. If the server does authorise the client, however, route the user to the 'my books' page.

**Additional context**
Branch: `0.2.0`

Note that you'll need to run the backend locally

### PR DESCRIPTION
**Pull request by danielhoeller**
## Summary of change

Added sendLoginRequest() to the Login component that sends a POST request to the /login endpoint and routes to /my-books if the request was successful; sets loginFailed state property to true otherwise.

Renders an error message, if loginFailed is true 

## Additional context

login

## Related issue

Closes #608 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by danielhoeller** [comment]
The error is
`Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1 or one of its dependencies could not be resolved: Could not transfer artifact info.picocli:picocli:jar:4.3.1`

No changes in the backend, so I'm guessing this is a random error?

**Comment by knjk04** [comment]
I think so. Not sure why that is, but I've created a separate issue for that

**Comment by knjk04** [comment]
Thanks for working on this! I'll review this shortly

**Comment by knjk04** [comment]
Could you please resolve the merge conflict?

**Comment by danielhoeller** [comment]
Okay I resolved the conflicts, but forgot I had formatOnSave turned on in VSCode, so there are a lot of changes in the Login component (I only realized after I pushed). As far as i can see, these changes in formatting are in line with the styleguide, so I'm wondering whether I can leave it as it is?

**Comment by knjk04** [comment]
That's fine

**Review by knjk04 — APPROVED** [review]
Thanks for working on this!

**Comment by knjk04** [comment]
And thanks for posting a gif!

**Pull request merged**
