### PR TITLE
Add Optionals

### LINKED ISSUE #356: Add Optionals
Where a null is used as a return type, change this to use an `Optional` instead. We don't want to use this for parameters

This is in line with a change to our style guide.

Branch: `0.2.0`

### PR DESCRIPTION
**Pull request by luisa01-code**
## Summary of change

added Optionals where there was an occurrence of "return null"

## Related issue

Closes #356 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
I've marked this as a draft while you're working on squashing the commits. Also, you may still have some compilation errors as the build is still failing?

As ever, if you need a hand, we'll be happy on Slack

**Comment by knjk04** [comment]
I noticed a compiler error and a merge conflict. Once you've resolved both, let us know and we can review this again

**Comment by luisa01-code** [comment]
I have solved the problem in RatingStatistics and only have two errors left, but I'm not able to finish those two. I asked in Slack for help :)

**Comment by knjk04** [comment]
Closing at your request on Slack

**Pull request closed without merging**
