### PR TITLE
Equals hash code 707

### LINKED ISSUE #707: Include author name in Book's equal() and hashCode()
Include the author name in Book's equal() and hashCode()

Branch from `0.2.0` and set it as the destination branch in your pull request

### PR DESCRIPTION
**Pull request by drunkenlegend**
## Summary of change

Added the author name in equals() and hashCode() for Book.
Additionally had to change the **FetchType** of Author to _Eager from Lazy_ as it gives the error where we try to fetch a lazy-loaded object from the database by using a proxy object, but the Hibernate session is already closed. (Also found some other ways to overcome the error but they are considered anti-pattern and hence proceeded this way.)

## Related issue

Closes #707  

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by drunkenlegend** [comment]
@knjk04 Can you please review my PR for #707, I am unable to rerun build on logs it says unable to connect to SonarCloud.

**Review by knjk04 — CHANGES_REQUESTED** [review]
@drunkenlegend Thanks for working on this. We want to keep the fetch type as lazy, so could you please change this back? (Sonarcloud problem is an open issue: https://github.com/Project-Books/book-project/issues/716)

**Comment by drunkenlegend** [comment]
Sure I can revert back the FetchType, however in Lazy fetch we are getting an error -
**_org.hibernate.LazyInitializationException: could not initialize proxy [com.karankumar.bookproject.backend.model.Author#1] - no Session_**
Would you suggest some other way to remove the error, here's a [link](https://www.baeldung.com/hibernate-initialize-proxy-exception) describing the error.

**Comment by knjk04** [comment]
Yes, you'll need to fix the error while keeping it set as lazy. This is one of the reasons we removed it. We are using entity graphs (see the Author class for an example) in some places to handle it. Have a look and see if you can get it to work if that. If not, I'll take a deeper dive to see if I can help you out

**Comment by drunkenlegend** [comment]
Sure, I'll take a look at Author class and get back to you if any other help is needed!

**Comment by drunkenlegend** [comment]
Its now working, I had to add the findAll() (using the NamedEntityGraph) function in BookRepository which is used in PredefinedShelfService on line 173.
However I am not totaly aware of the use case in PredefinedShelfService, that why are we not using the findAllBooks() method which we have already defined in the BookRepository, this will save us from adding NamedEntityGraph in Book.

**Review by knjk04 — CHANGES_REQUESTED** [review]
Thanks for working on this.

> Include the author name in Book's equal() and hashCode()

Note that the issue description specifies to include the author name in the equals() method for Book, but it's not included.

Here's how I tested this:
image

This was the output:
```
Book{title='title'}
```

Could you please fix this?

**Comment by drunkenlegend** [comment]
Thanks @knjk04 for pointing that out.
The possible reason for author not getting as output was I hadn't modified the toString() in Book Class, but equalsAndHashCode had been included in the Book Class for Author.
Screenshot from 2021-08-28 23-36-15

I have now modified the toString() and output is like:
`Book{title='title', author=firstName lastName}`
If there is some other way we can directly check the attributes in equal() and hashCode() please guide me.

**Review by knjk04 — APPROVED** [review]
Thanks for making the change!

**Pull request merged**
