### PR TITLE
Add class diagram 

### LINKED ISSUE #351: Create class diagram for classes in the entities package
Create an entity-relationship diagram for our Java entities using [JDL-studio](https://start.jhipster.tech/jdl-studio/). This could help onboard new contributors quicker.

If you want to use a different tool, let us know before implementing it

Update: create a class diagram, not an ER diagram

### PR DESCRIPTION
**Pull request by Anoop01234**
Added the class diagram of Project-Book

Added the new branch and added the architecture to it.

## Additional context

@knjk04 sir I have created a new branch and added the architecture.
(In the entity folder under the Architechture.md file also the media in the readme folder in media folder)
Also, changes to be made in the coming future are welcome.

image

## Related issue

Closes #351 

Also, see the closed PR #466 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for updating the diagram. `Shelf` now takes a `User`, so could you please add `User` and `Role` into the diagram?

**Comment by knjk04** [comment]
Also, could you please add the new book format and ISBN attributes?

**Comment by Anoop01234** [comment]
So these are the variables under `BOOK` class? (Also, here ISBN is of int data type and Book format is of String data type?)

**Comment by knjk04** [comment]
@Anoop01234 

> So these are the variables under BOOK class?

Yes

> (Also, here ISBN is of int data type and Book format is of String data type?)

ISBN is an int, but BookFormat should be an enum

**Comment by knjk04** [comment]
@Anoop01234 I noticed you pushed again. Feel free to let usk know when you'd like another review

**Comment by Anoop01234** [comment]
Are the previous changes alright @knjk04 sir?

**Comment by knjk04** [comment]
@Anoop01234 Some feedback:

- I don't think you added the ISBN and book format to the book entity. The `BookFormat` class will also need to be in the diagram
- `Book` inherits from `BaseEntity`, so the arrow should be facing towards `BaseEntity`
- `PredefinedShelf` inherits from `Shelf`, so the arrow should be facing towards `Shelf`
- We have getters and setters for all fields in the entities. I think it'll clutter the diagram, however, so could you please remove the method section of each entity?

**Comment by knjk04** [comment]
@Anoop01234 Thanks for renaming the file. Could you please address the other feedback I left in my last comment and then let us know once you've done that?

**Comment by Anoop01234** [comment]
@knjk04 sir, could you tell attributes and functions of BookFormat class, since I cannot find it in any file.
Also, I didn't get the 3rd last point, where you mentioned removing methods.

**Comment by knjk04** [comment]
@Anoop01234 You can find the BookFormat class [here](https://github.com/Project-Books/book-project/blob/master/src/main/java/com/karankumar/bookproject/backend/entity/BookFormat.java)

> Also, I didn't get the 3rd last point, where you mentioned removing methods.

image

I've highlighted the methods for you here. Could you please remove the second half of each box?

**Comment by Anoop01234** [comment]
@knjk04 I have made the required changes. Please review it once.

**Comment by knjk04** [comment]
@Anoop01234 Thanks for making the changes.

- I've renamed the heading, so I recommend pulling before working on this again
- The Book and Book format relationship is the wrong way around
- Could you please export your work on Lucidchart as a Lucidspark file (File > Export > Lucidspark)?

**Comment by knjk04** [comment]
@Anoop01234 How are you getting on with addressing the suggestions?

**Comment by Anoop01234** [comment]
Sorry for the delay sir, but I have my mid-term exams going on from 1st Nov to 12th Nov. So I'd be able to devote my full time after 12th Nov.

**Comment by knjk04** [comment]
@Anoop01234 No problem. Thanks for the update and best of luck with your exams!

**Comment by Anoop01234** [comment]
@knjk04 sir, I have made the changes to the book format and book relationship.
Also, I'd like to mention that Lucidspark is a premium feature of Lucidchart, therefore, I wasn't able to carry out the third point.

**Comment by knjk04** [comment]
image

Thanks for making the changes.

Could you please change the highlighted aggregation relationships to composition?

> Also, I'd like to mention that Lucidspark is a premium feature of Lucidchart, therefore, I wasn't able to carry out the third point.

Oh, OK. I didn't know that. That's fine then

**Comment by Anoop01234** [comment]
I have made the changes @knjk04 sir.

**Review by knjk04 — APPROVED** [review]
Thanks for making the changes & working on this!

**Pull request merged**
