### PR TITLE
add year of publication to Book entity

### LINKED ISSUE #493: Add year of publication to the Book entity
**Describe the solution you'd like**
Add a year of publication attribute to the `Book` entity. This should be an optional field.

---

If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace

### PR DESCRIPTION
**Pull request by michiboo**
## Summary of change

add year of publication to Book entity. 
Should the data type of year of publication be INT?

Closes #493

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this! 

> private Integer yearof_publication;

Could you please change this to camel case (in line with our style guide)?

Also, could you please:

- Add a Flyway migration
- Create a method in `TestData.java` that generates a random year (reasonable lower bound & 2020 for the upper)
- Set the year of publication for every book created in `TestData.java`

**Comment by knjk04** [comment]
I've marked this PR as a draft. Feel free to click on the 'ready for review' button below when you're ready

**Comment by michiboo** [comment]
@knjk04 How can I add a Flyway migration? sorry I wasn't so familiar with it.

**Comment by knjk04** [comment]
@michiboo You can add a new column in an SQL script. In this case, it should be similar to this [example](https://github.com/Project-Books/book-project/blob/master/src/main/resources/db/migration/V015__ALTER_BOOK_ADD_ISBN.sql)

**Review by knjk04 — APPROVED** [review]
All good. Thanks for working on this!

**Pull request merged**
