### PR TITLE
Setting up proxy middleware to prevent proxy errors while running frontend in Docker

### LINKED ISSUE #912: Proxy error: Could not proxy request /api/shelf/books/read from localhost:3000 to http://localhost:8080.
**Describe the bug**

When running the frontend in a docker container, I get a proxy error:

```
frontend-dev | Proxy error: Could not proxy request /api/shelf/books/reading from localhost:3000 to http://localhost:8080.
frontend-dev | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

Log: https://gist.github.com/knjk04/0d7e7dca7fb1394030b707a60c60580c

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the frontend using Docker (see instructions in the README)
2. Log in with the test user credentials
3. Inspect network tab
4. Go to list view
5. See error

**Expected behaviour**

200 OK API calls.

**Your system**

If it's frontend-related, tell us which 
- Browser and browser version you see the bug on
- your Node and npm versions

For backend-related bugs, tell us your 
- operating system
- which type of JDK you're running (e.g. Oracle JDK or OpenJDK)
- JDK version number (including the minor and patch version) 
- which IDE and version you're using (if relevant)

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

### PR DESCRIPTION
**Pull request by priya1712d**
## Summary of change

Setting up proxy middleware to prevent proxy errors while running frontend in Docker

## Related issue

Closes #912

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

### CODE REVIEW

**Comment by priya1712d** [comment]
Hi @knjk04
I am new to frontend technologies, could you help in resolving this yarn conflict.

**Comment by knjk04** [comment]
Hi @priya1712d, I've resolved the merge conflict. I noticed your fork was far behind the `main` branch, so you may want to look into create an upstream remote branch and then fetching from it periodically to ensure your fork remains in sync with this repository (see https://project-books.github.io/docs/development/contributing/#syncing-your-fork)

**Review by knjk04 — CHANGES_REQUESTED** [review]
@priya1712d Thanks for working on this!

image

I noticed that no books are showing anymore and we are getting a syntax error. Would it be possible for you to look into this?

**Comment by knjk04** [comment]
@priya1712d Ah, I see. I'll merge this one and create a separate issue for that. Having separate environment files sounds good. One thing I was noticed was that the frontend can still hit the /login endpoint, just not any others

**Review by knjk04 — APPROVED** [review]

**Comment by DucNgn** [comment]
Hi @knjk04 @priya1712d 

I'm trying to set it up with Docker and Docker compose as in the README file.
I'm still having the same issue that you described before with the latest on `main`.

The books are not displayed correctly and all the buttons are not functional:

image

Here are some of the logs:

```
book_project_frontend | Proxy error: Could not proxy request /api/shelf/books/reading from localhost:3000 to http://backend:8080/.
book_project_frontend | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
book_project_frontend |

```

So I think it's an issue with Dockerized app like you mentioned. Could you provide a quick fix or maybe a workaround in the meantime for this issue?

Thank you!

**Pull request merged**
