### PR TITLE
Add optionals 356

### LINKED ISSUE #356: Add Optionals
Where a null is used as a return type, change this to use an `Optional` instead. We don't want to use this for parameters

This is in line with a change to our style guide.

Branch: `0.2.0`

### PR DESCRIPTION
**Pull request by hieu-t-tran**
## Summary of change

Update the code to use `Optional` instead of `null`. This is a continuation from PR #542.

## Related issue

Closes #356

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [X] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [X] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [X] Ensure code changes pass all tests

- [X] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [X] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [X] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [X] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [X] Set this pull request to 'draft' if you are still working on it

- [X] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by hieu-t-tran** [comment]
Could you have a look at this and see if there is any additional work needed to be done? Thank you so much!

**Comment by knjk04** [comment]
Sure, will do. Thanks for working on this!

**Comment by knjk04** [comment]
I'll take a look at this over the weekend. Apologies for the delay

**Comment by hieu-t-tran** [comment]
No worries, please take your time. Thank you!

**Review by knjk04 — APPROVED** [review]
Thanks for working on this!

**Pull request merged**
