### PR TITLE
refactored navbar to use flex and be responsive

### LINKED ISSUE #605: Make the app bar responsive
**Describe the bug**

Some of the navigation items do not always show in the app bar.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `localhost:8080/my-books`
2. See error

**Expected behaviour**

**Screenshots**

This shows as intended on a 2560x1440 screen:

image

Some items not visible on lower resolutions, e.g.: 
image

**Additional context**

Branch: `0.2.0`

### PR DESCRIPTION
**Pull request by RivaD2**
## Summary of change

My approach: Implement flexbox use on `NavBar.css` and make necessary changes to `NavBar.tsx` for app bar responsiveness. Areas of concern were original `#gap` style, `padding-top` style and `height:100%` style on `.nav-bar`.

- Added `package-lock.json` to .gitignore
- Separated out the Links at the top of the page(and the logo) into their own `<div>` and the Links at the bottom into their own `<div>`.
- I then  added `padding-top` to the separated out  Logo Link rather than `nav-bar` itself using className `.nav-top`. I took the original `#gap` styles and applied the padding-bottom only to the top divs, pushing the other links down where they should be.
- I applied additional flex properties and added the `nav-links` className to links at bottom as well. 
- The app bar is now responsive as the height increases in size.

## Additional context

- Below is a shot of app bar at 744X735
app-bar1

- Below is a shot of app bar at 744X536

## Related issue

Closes #605

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests **NO testing done**

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by RivaD2** [comment]
@knjk04 I am ready for review! My approach was to use Flexbox and basically put links inside their own divs. There were also some additional changes to be made, such as removing the #gap height and adding the padding to the logo itself rather than the entire nav bar. The app bar is now responsive :)

**Comment by knjk04** [comment]
Thanks, Riva! I'll review this soon

**Comment by knjk04** [comment]
Could you please rebase and resolve the merge conflict? Bringing your branch level with 0.2.0 should fix that failing build

**Comment by RivaD2** [comment]
@knjk04 I had the repo cloned, so I went to the branch and did a fetch/pull before doing work. Then I brought my branch level with 0.2.0, and branched off for work. Do you have any advice on the easiest way to avoid having to rebase? I must be missing a step when bringing my branch level with 0.2.0.

Thank you for your help!

**Comment by knjk04** [comment]
If you don't want to rebase, you can pull from 0.2.0 and then merge it into your feature branch:

1. If you haven't already, create a remote that points to this repository. See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork 
2. Switch to 0.2.0 (e.g. `git checkout 0.2.0`)
3. Pull: `git pull upstream 0.2.0` (this will pull the version on this repository, not your fork. Your fork's remote name will be 'origin', whereas this repository will be called 'upstream')
4. Switch back to your feature branch
5. Merge 0.2.0 into your feature branch: `git merge 0.2.0`

**Comment by RivaD2** [comment]
@knjk04 Perfect, thank you! I had set up a remote and I thought I had performed all those steps correctly, but I was using a GUI and must have missed something. I shall make the fix :)

**Comment by RivaD2** [comment]
@knjk04 I went in and did the pull from upstream 0.2.0 and resolved merge conflicts. The merge conflict came from whitespace clean up from another branch and it looks like there was some additional linter rules added so I added a return type to the Class in `NavBar.tsx`. 

All appears to be good now :)

**Review by knjk04 — APPROVED** [review]
Thanks a lot for working on this! The summary, in particular, was helpful! 

I've taken package-lock out of the .gitignore file as we still want to keep it under version control

**Comment by RivaD2** [comment]
@knjk04 It is my pleasure to help! I'm learning a lot/solidifying other skills each time I help.  I've never worked in a codebase this large before and I feel this is really good experience for me. Thank you for your help thus far :)

**Comment by knjk04** [comment]
@RivaD2 It's great to hear you feel like you're learning a lot! Having a strong lifelong learning mentality is excellent!

**Pull request merged**
